Repository KPT-Final-Team9/back9, pull requests merged in 2024-05, with the labels that each got.

#1 test : github - discord Webhook 테스트
  src/main/java/com/core/back9/test/TestClass.java
Labels: test

#3 ERD 작성 내용에 맞춘 엔티티 클래스 생성
  src/main/java/com/core/back9/common/config/DemoConfig.java
  src/main/java/com/core/back9/common/constant/SignType.java
  src/main/java/com/core/back9/common/constant/Status.java
  src/main/java/com/core/back9/controller/DemoController.java
  src/main/java/com/core/back9/entity/Buildings.java
  src/main/java/com/core/back9/entity/ComplaintScores.java
  src/main/java/com/core/back9/entity/Contracts.java
  src/main/java/com/core/back9/entity/FacilityScores.java
  src/main/java/com/core/back9/entity/ManagementScores.java
  src/main/java/com/core/back9/entity/Members.java
  src/main/java/com/core/back9/entity/Rooms.java
  src/main/java/com/core/back9/entity/Settings.java
  src/main/java/com/core/back9/entity/Tenants.java
  src/main/java/com/core/back9/entity/constant/ContractStatus.java
  src/main/java/com/core/back9/entity/constant/Role.java
  src/main/java/com/core/back9/entity/constant/RoomStatus.java
  src/main/java/com/core/back9/repository/DemoRepository.java
  src/main/java/com/core/back9/service/DemoService.java
  src/main/java/com/core/back9/test/TestClass.java
Labels: enhancement

#5 Add #4 : ObjectMapper 설정 생성
  src/main/java/com/core/back9/common/config/ObjectMapperConfig.java
Labels: enhancement

#7 add #6 : BaseEntity 생성 및 연결, AuditingConfig 생성, Score 엔티티 통합, yml파일 생성
  .docker/Dockerfile
  src/main/java/com/core/back9/common/config/AuditingConfig.java
  src/main/java/com/core/back9/common/config/DemoConfig.java
  src/main/java/com/core/back9/common/constant/SignType.java
  src/main/java/com/core/back9/common/constant/Status.java
  src/main/java/com/core/back9/common/entity/BaseEntity.java
  src/main/java/com/core/back9/entity/Buildings.java
  src/main/java/com/core/back9/entity/ComplaintScores.java
  src/main/java/com/core/back9/entity/Contracts.java
  src/main/java/com/core/back9/entity/ManagementScores.java
  src/main/java/com/core/back9/entity/Members.java
  src/main/java/com/core/back9/entity/Rooms.java
  src/main/java/com/core/back9/entity/Scores.java
  src/main/java/com/core/back9/entity/Settings.java
  src/main/java/com/core/back9/entity/Tenants.java
  src/main/java/com/core/back9/entity/constant/RatingType.java
  src/main/java/com/core/back9/entity/constant/SignType.java
  src/main/java/com/core/back9/entity/constant/Status.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#9 Add #8 : ERD 신규 등록
  final-9.svg
Labels: documentation

#14 SwaggerConfig, WebMvcConfig 생성
  build.gradle
  src/main/java/com/core/back9/common/config/SwaggerConfig.java
  src/main/java/com/core/back9/common/config/WebMvcConfig.java
  src/main/resources/application.yml
Labels: documentation, enhancement

#16 수정 이전 Entity삭제, templete 수정
  .github/ISSUE_TEMPLATE/back9-issue-templete.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/core/back9/entity/Buildings.java
  src/main/java/com/core/back9/entity/Contracts.java
  src/main/java/com/core/back9/entity/Members.java
  src/main/java/com/core/back9/entity/Tenants.java
Labels: documentation, enhancement

#23 빌딩 CRUD
  README.md
  src/main/java/com/core/back9/common/config/ModeResolverConfig.java
  src/main/java/com/core/back9/controller/BuildingController.java
  src/main/java/com/core/back9/dto/BuildingDTO.java
  src/main/java/com/core/back9/entity/Building.java
  src/main/java/com/core/back9/entity/constant/Status.java
  src/main/java/com/core/back9/exception/ApiErrorCode.java
  src/main/java/com/core/back9/mapper/BuildingMapper.java
  src/main/java/com/core/back9/repository/BuildingRepository.java
  src/main/java/com/core/back9/service/BuildingService.java
Labels: enhancement

#25 예외 메시지 분기 처리
  src/main/java/com/core/back9/common/config/AsyncConfig.java
  src/main/java/com/core/back9/exception/ApiErrorCode.java
  src/main/java/com/core/back9/exception/ApiExceptionHandler.java
Labels: development

#28 배포 스크립트 최종 확정
  .docker/docker-compose.yml
  scripts/deploy.sh
  src/main/resources/application.yml
Labels: documentation

#34 빌딩 CRUD 레이어별 단위 테스트 구현
  src/test/java/com/core/back9/controller/BuildingControllerTest.java
  src/test/java/com/core/back9/repository/BuildingRepositoryTest.java
  src/test/java/com/core/back9/service/BuildingServiceTest.java
Labels: enhancement

#36 매퍼 옵션추가, ModelResolver 오타 수정, deploy script 수정
  scripts/deploy.sh
  src/main/java/com/core/back9/common/config/ModelResolverConfig.java
  src/main/java/com/core/back9/mapper/ContractMapper.java
  src/main/java/com/core/back9/mapper/MemberMapper.java
  src/main/java/com/core/back9/mapper/RoomMapper.java
  src/main/java/com/core/back9/mapper/ScoreMapper.java
  src/main/java/com/core/back9/mapper/SettingMapper.java
  src/main/java/com/core/back9/mapper/TenantMapper.java
Labels: development

#38 Room 엔티티 수정(RoomStatus 제거)
  src/main/java/com/core/back9/dto/RoomDTO.java
  src/main/java/com/core/back9/entity/Room.java
  src/main/java/com/core/back9/entity/constant/RoomStatus.java
  src/main/resources/db/migration/V2__room-update.sql
Labels: fix

#43 Member password 필드 추가 및 migration 파일 추가
  src/main/java/com/core/back9/entity/Member.java
  src/main/resources/db/migration/V3__member-password.sql
Labels: documentation

#44 호실 CRUD 기능 구현과 테스트
  src/main/java/com/core/back9/controller/RoomController.java
  src/main/java/com/core/back9/dto/RoomDTO.java
  src/main/java/com/core/back9/entity/Room.java
  src/main/java/com/core/back9/entity/constant/ContractStatus.java
  src/main/java/com/core/back9/entity/constant/Usage.java
  src/main/java/com/core/back9/exception/ApiErrorCode.java
  src/main/java/com/core/back9/mapper/RoomMapper.java
  src/main/java/com/core/back9/repository/RoomRepository.java
  src/main/java/com/core/back9/service/BuildingService.java
  src/main/java/com/core/back9/service/RoomService.java
  src/test/java/com/core/back9/controller/RoomControllerTest.java
  src/test/java/com/core/back9/repository/BuildingRepositoryTest.java
  src/test/java/com/core/back9/repository/RoomRepositoryTest.java
  src/test/java/com/core/back9/service/RoomServiceTest.java
Labels: enhancement, development, fix

#46 contract CRUD 구현
  src/main/java/com/core/back9/controller/ContractController.java
  src/main/java/com/core/back9/controller/TenantController.java
  src/main/java/com/core/back9/dto/ContractDTO.java
  src/main/java/com/core/back9/dto/TenantDTO.java
  src/main/java/com/core/back9/entity/Contract.java
  src/main/java/com/core/back9/entity/Tenant.java
  src/main/java/com/core/back9/entity/constant/ContractStatus.java
  src/main/java/com/core/back9/exception/ApiErrorCode.java
  src/main/java/com/core/back9/mapper/ContractMapper.java
  src/main/java/com/core/back9/mapper/TenantMapper.java
  src/main/java/com/core/back9/repository/ContractRepository.java
  src/main/java/com/core/back9/repository/DemoRepository.java
  src/main/java/com/core/back9/repository/TenantRepository.java
  src/main/java/com/core/back9/service/ContractService.java
  src/main/java/com/core/back9/service/DemoService.java
  src/main/java/com/core/back9/service/TenantService.java
  src/main/resources/application.yml
  src/test/java/com/core/back9/mapper/ContractMapperTest.java
  src/test/java/com/core/back9/mapper/TenantMapperTest.java
  src/test/java/com/core/back9/repository/TenantRepositoryTest.java
Labels: development

#49 메일 발송 컴포넌트 추가
  build.gradle
  src/main/java/com/core/back9/common/config/MailConfig.java
  src/main/java/com/core/back9/common/service/MailManager.java
Labels: enhancement

#51 ERD 수정
  final-9.svg
Labels: documentation, development

#54 호실-설정-계약서 관계 설정
  src/main/java/com/core/back9/entity/Room.java
  src/main/java/com/core/back9/entity/Setting.java
  src/main/resources/db/migration/V5__settings-message.sql
  src/main/resources/db/migration/V6__room-include-contract.sql
Labels: development

#55 호실 설정 기능 구현
  src/main/java/com/core/back9/controller/BuildingController.java
  src/main/java/com/core/back9/controller/RoomController.java
  src/main/java/com/core/back9/dto/RoomDTO.java
  src/main/java/com/core/back9/dto/SettingDTO.java
  src/main/java/com/core/back9/entity/Room.java
  src/main/java/com/core/back9/entity/Setting.java
  src/main/java/com/core/back9/mapper/BuildingMapper.java
  src/main/java/com/core/back9/mapper/RoomMapper.java
  src/main/java/com/core/back9/mapper/SettingMapper.java
  src/main/java/com/core/back9/repository/RoomRepository.java
  src/main/java/com/core/back9/repository/SettingRepository.java
  src/main/java/com/core/back9/service/BuildingService.java
  src/main/java/com/core/back9/service/RoomService.java
  src/main/resources/db/migration/V7__room-include-default-setting.sql
  src/test/java/com/core/back9/controller/BuildingControllerTest.java
  src/test/java/com/core/back9/controller/RoomControllerTest.java
  src/test/java/com/core/back9/repository/RoomRepositoryTest.java
  src/test/java/com/core/back9/service/BuildingServiceTest.java
  src/test/java/com/core/back9/service/RoomServiceTest.java
Labels: enhancement, development, fix

#56 Spring Security, JWT 관련 설정, Member 관련 기본 기능 구현
  build.gradle
  src/main/java/com/core/back9/common/config/SecurityConfig.java
  src/main/java/com/core/back9/common/util/SecurityUtil.java
  src/main/java/com/core/back9/controller/MemberController.java
  src/main/java/com/core/back9/controller/MemberPublicController.java
  src/main/java/com/core/back9/dto/MemberDTO.java
  src/main/java/com/core/back9/dto/TokenDTO.java
  src/main/java/com/core/back9/entity/constant/Role.java
  src/main/java/com/core/back9/exception/ApiErrorCode.java
  src/main/java/com/core/back9/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/core/back9/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/core/back9/jwt/JwtAuthenticationFilter.java
  src/main/java/com/core/back9/jwt/JwtProvider.java
  src/main/java/com/core/back9/mapper/MemberMapper.java
  src/main/java/com/core/back9/repository/MemberRepository.java
  src/main/java/com/core/back9/service/CustomUserDetailsService.java
  src/main/java/com/core/back9/service/MemberService.java
Labels: enhancement

#59 Contract 도메인 기본 기능 구현 및 관련 테스트 코드 작성
  src/main/java/com/core/back9/controller/ContractController.java
  src/main/java/com/core/back9/entity/Contract.java
  src/main/java/com/core/back9/entity/Room.java
  src/main/java/com/core/back9/entity/constant/ContractType.java
  src/main/java/com/core/back9/exception/ApiErrorCode.java
  src/main/java/com/core/back9/mapper/ContractMapper.java
  src/main/java/com/core/back9/repository/ContractRepository.java
  src/main/java/com/core/back9/repository/TenantRepository.java
  src/main/java/com/core/back9/service/ContractService.java
  src/main/java/com/core/back9/service/TenantService.java
  src/main/resources/db/migration/V8__contract-mapping-room.sql
  src/main/resources/db/migration/V9__drop-index-room-tenant.sql
  src/test/java/com/core/back9/mapper/ContractMapperTest.java
  src/test/java/com/core/back9/repository/ContractRepositoryTest.java
  src/test/java/com/core/back9/repository/TenantRepositoryTest.java
  src/test/java/com/core/back9/repository/fixture/ContractFixture.java
Labels: enhancement, development

#67 Contract 상태 변경 기능 관련 도메인 단위 로직 추가
  src/main/java/com/core/back9/controller/TenantController.java
  src/main/java/com/core/back9/controller/TenantPublicController.java
  src/main/java/com/core/back9/dto/ContractDTO.java
  src/main/java/com/core/back9/entity/Contract.java
  src/main/java/com/core/back9/entity/constant/ContractStatus.java
  src/main/java/com/core/back9/exception/ApiErrorCode.java
  src/main/java/com/core/back9/mapper/ContractMapper.java
  src/test/java/com/core/back9/entity/ContractTest.java
  src/test/java/com/core/back9/mapper/ContractMapperTest.java
  src/test/java/com/core/back9/repository/ContractRepositoryTest.java
Labels: enhancement, development

#70 Contract 상태 변경 비즈니스 로직 추가
  src/main/java/com/core/back9/controller/ContractController.java
  src/main/java/com/core/back9/dto/ContractDTO.java
  src/main/java/com/core/back9/entity/Contract.java
  src/main/java/com/core/back9/mapper/ContractMapper.java
  src/main/java/com/core/back9/service/ContractService.java
  src/test/java/com/core/back9/entity/ContractTest.java
  src/test/java/com/core/back9/repository/ContractRepositoryTest.java
  src/test/java/com/core/back9/repository/fixture/ContractRepositoryFixture.java
  src/test/java/com/core/back9/service/ContractServiceTest.java
  src/test/java/com/core/back9/service/fixture/ContractServiceFixture.java
Labels: enhancement, development

#72 Role이 다르면 이메일과 전화번호가 중복이어도 회원가입이 가능하도록 수정
  src/main/java/com/core/back9/controller/MemberController.java
  src/main/java/com/core/back9/controller/MemberPublicController.java
  src/main/java/com/core/back9/repository/MemberRepository.java
  src/main/java/com/core/back9/service/MemberService.java
Labels: development

#75 빌딩 도메인 기능 고도화
  src/main/java/com/core/back9/controller/BuildingController.java
  src/main/java/com/core/back9/dto/BuildingDTO.java
  src/main/java/com/core/back9/service/BuildingService.java
  src/test/java/com/core/back9/controller/BuildingControllerTest.java
  src/test/java/com/core/back9/service/BuildingServiceTest.java
Labels: development

#78 호실 기능 고도화 구현
  src/main/java/com/core/back9/controller/RoomController.java
  src/main/java/com/core/back9/dto/MemberDTO.java
  src/main/java/com/core/back9/dto/RoomDTO.java
  src/main/java/com/core/back9/entity/Room.java
  src/main/java/com/core/back9/mapper/MemberMapper.java
  src/main/java/com/core/back9/mapper/RoomMapper.java
  src/main/java/com/core/back9/repository/MemberRepository.java
  src/main/java/com/core/back9/service/RoomService.java
  src/test/java/com/core/back9/controller/BuildingControllerTest.java
  src/test/java/com/core/back9/controller/RoomControllerTest.java
  src/test/java/com/core/back9/repository/BuildingRepositoryTest.java
  src/test/java/com/core/back9/repository/RoomRepositoryTest.java
  src/test/java/com/core/back9/service/BuildingServiceTest.java
  src/test/java/com/core/back9/service/RoomServiceTest.java
Labels: enhancement, development

#80 Tenant, Contract 도메인 상위 엔티티와 연결 및 계약 등록 관련 로직 개선
  src/main/java/com/core/back9/common/config/SwaggerConfig.java
  src/main/java/com/core/back9/controller/ContractController.java
  src/main/java/com/core/back9/controller/TenantController.java
  src/main/java/com/core/back9/dto/ContractDTO.java
  src/main/java/com/core/back9/mapper/ContractMapper.java
  src/main/java/com/core/back9/repository/ContractRepository.java
  src/main/java/com/core/back9/repository/RoomRepository.java
  src/main/java/com/core/back9/service/ContractService.java
  src/main/java/com/core/back9/service/TenantService.java
  src/test/java/com/core/back9/mapper/ContractMapperTest.java
  src/test/java/com/core/back9/service/ContractServiceTest.java
  src/test/java/com/core/back9/service/fixture/ContractServiceFixture.java
Labels: enhancement, development

#82 호실-계약 연관관계 추가 구현
  src/main/java/com/core/back9/dto/ContractDTO.java
  src/main/java/com/core/back9/dto/RoomDTO.java
  src/main/java/com/core/back9/dto/TenantDTO.java
  src/main/java/com/core/back9/entity/Room.java
  src/main/java/com/core/back9/mapper/ContractMapper.java
  src/main/java/com/core/back9/mapper/RoomMapper.java
  src/main/java/com/core/back9/mapper/TenantMapper.java
  src/main/java/com/core/back9/service/ContractService.java
Labels: enhancement, development

#86 평가 레코드 생성 구현
  src/main/java/com/core/back9/controller/RoomController.java
  src/main/java/com/core/back9/dto/ScoreDTO.java
  src/main/java/com/core/back9/entity/Score.java
  src/main/java/com/core/back9/entity/Tenant.java
  src/main/java/com/core/back9/entity/constant/RatingType.java
  src/main/java/com/core/back9/mapper/ScoreMapper.java
  src/main/java/com/core/back9/repository/ScoreRepository.java
  src/main/java/com/core/back9/service/ScoreService.java
Labels: enhancement

#89 평가 관련 추가 구현
  src/main/java/com/core/back9/controller/MemberController.java
  src/main/java/com/core/back9/controller/ScoreController.java
  src/main/java/com/core/back9/dto/DateDTO.java
  src/main/java/com/core/back9/entity/Member.java
  src/main/java/com/core/back9/entity/Score.java
  src/main/java/com/core/back9/entity/Tenant.java
  src/main/java/com/core/back9/exception/ApiErrorCode.java
  src/main/java/com/core/back9/repository/ScoreRepository.java
  src/main/java/com/core/back9/service/ScoreService.java
  src/main/java/com/core/back9/util/DateUtils.java
  src/test/java/com/core/back9/repository/ScoreRepositoryTest.java
  src/test/java/com/core/back9/service/RoomServiceTest.java
  src/test/java/com/core/back9/service/ScoreServiceTest.java
Labels: enhancement, development, fix

#93 평가 상세 페이지 조회 기능 구현
  src/main/java/com/core/back9/controller/OwnerScoreController.java
  src/main/java/com/core/back9/controller/UserScoreController.java
  src/main/java/com/core/back9/repository/ScoreRepository.java
  src/main/java/com/core/back9/service/ScoreService.java
  src/main/java/com/core/back9/util/EvaluationSpecifications.java
  src/test/java/com/core/back9/repository/ScoreRepositoryTest.java
  src/test/java/com/core/back9/service/ScoreServiceTest.java
Labels: enhancement, development

#97 ContractTasklet 세부내용 작성
  src/main/java/com/core/back9/batch/job/ContractBatchJob.java
  src/main/java/com/core/back9/batch/property/BatchPropertyConfig.java
  src/main/java/com/core/back9/batch/scheduler/BatchScheduler.java
  src/main/java/com/core/back9/batch/scheduler/ContractBatchScheduler.java
  src/main/java/com/core/back9/batch/scheduler/TestBatchScheduler.java
  src/main/java/com/core/back9/batch/tasklet/ContractExpireTasklet.java
  src/main/java/com/core/back9/batch/tasklet/ContractInProgressTasklet.java
  src/main/java/com/core/back9/batch/tasklet/ContractTasklet.java
  src/main/java/com/core/back9/repository/ContractRepository.java
Labels: enhancement

#98 빌딩, 호실 컨트롤러 분리
  src/main/java/com/core/back9/controller/BuildingController.java
  src/main/java/com/core/back9/controller/OwnerBuildingController.java
  src/main/java/com/core/back9/controller/OwnerRoomController.java
  src/main/java/com/core/back9/controller/RoomController.java
  src/main/java/com/core/back9/repository/BuildingRepository.java
  src/main/java/com/core/back9/repository/RoomRepository.java
  src/main/java/com/core/back9/service/BuildingService.java
  src/main/java/com/core/back9/service/RoomService.java
Labels: development
