Repository KPT-Final-Team9/back9, pull requests merged in 2024-06, with the labels that each got.

#101 호실 상세페이지 데이터 가공
  src/main/java/com/core/back9/controller/OwnerScoreController.java
  src/main/java/com/core/back9/dto/ScoreDTO.java
  src/main/java/com/core/back9/service/ScoreService.java
  src/main/java/com/core/back9/util/EvaluationSpecifications.java
Labels: enhancement

#104 내호실 및 비교 호실 보증금/임대료 조회 로직 구현
  src/main/java/com/core/back9/batch/job/ContractBatchJob.java
  src/main/java/com/core/back9/batch/tasklet/ContractInProgressTasklet.java
  src/main/java/com/core/back9/controller/ContractController.java
  src/main/java/com/core/back9/dto/ContractDTO.java
  src/main/java/com/core/back9/mapper/ContractMapper.java
  src/main/java/com/core/back9/repository/ContractRepository.java
  src/main/java/com/core/back9/service/ContractService.java
  src/test/java/com/core/back9/mapper/ContractMapperTest.java
  src/test/java/com/core/back9/repository/ContractRepositoryTest.java
  src/test/java/com/core/back9/service/ContractServiceTest.java
Labels: enhancement, development

#105 대시보드 데이터 가공
  src/main/java/com/core/back9/controller/OwnerBuildingController.java
  src/main/java/com/core/back9/controller/OwnerScoreController.java
  src/main/java/com/core/back9/controller/RoomController.java
  src/main/java/com/core/back9/dto/DateDTO.java
  src/main/java/com/core/back9/dto/ScoreDTO.java
  src/main/java/com/core/back9/service/ScoreService.java
  src/main/java/com/core/back9/util/DateUtils.java
  src/main/java/com/core/back9/util/EvaluationSpecifications.java
Labels: development

#108 내 호실 및 선택된 빌딩의 타 호실 평균 재계약률 조회 로직 구성
  src/main/java/com/core/back9/controller/ContractController.java
  src/main/java/com/core/back9/dto/ContractDTO.java
  src/main/java/com/core/back9/mapper/ContractMapper.java
  src/main/java/com/core/back9/repository/ContractRepository.java
  src/main/java/com/core/back9/service/ContractService.java
  src/test/java/com/core/back9/repository/ContractRepositoryTest.java
  src/test/java/com/core/back9/service/ContractServiceTest.java
Labels: enhancement

#109 대시보드 데이터 가공 추가 작업
  src/main/java/com/core/back9/controller/BuildingController.java
  src/main/java/com/core/back9/controller/OwnerBuildingController.java
  src/main/java/com/core/back9/controller/OwnerRoomController.java
  src/main/java/com/core/back9/controller/OwnerScoreController.java
  src/main/java/com/core/back9/dto/ScoreDTO.java
  src/main/java/com/core/back9/mapper/ScoreMapper.java
  src/main/java/com/core/back9/service/ScoreService.java
  src/main/java/com/core/back9/util/EvaluationSpecifications.java
Labels: enhancement, development

#111 비교 호실의 재계약률을 평균하는 과정에서 소수점 둘째자리까지 출력되는 이슈 해결
  src/main/java/com/core/back9/service/ContractService.java
  src/test/java/com/core/back9/service/ContractServiceTest.java
Labels: development

#113 평가 레코드 생성 관련 배치 작업
  src/main/java/com/core/back9/batch/job/FacilityScoreBatchJob.java
  src/main/java/com/core/back9/batch/job/ManagementScoreBatchJob.java
  src/main/java/com/core/back9/batch/property/BatchPropertyConfig.java
  src/main/java/com/core/back9/batch/scheduler/FacilityScoreBatchScheduler.java
  src/main/java/com/core/back9/batch/scheduler/ManagementScoreBatchScheduler.java
  src/main/java/com/core/back9/batch/tasklet/FacilityScoreTasklet.java
  src/main/java/com/core/back9/batch/tasklet/ManagementScoreTasklet.java
  src/main/java/com/core/back9/repository/ContractRepository.java
  src/main/java/com/core/back9/security/AuthMember.java
Labels: enhancement

#117 임대료, 재계약률, 공실률 로직 컨트롤러와 연결
  src/main/java/com/core/back9/controller/ContractController.java
  src/main/java/com/core/back9/dto/ContractDTO.java
  src/main/java/com/core/back9/mapper/ContractMapper.java
  src/main/java/com/core/back9/service/ContractService.java
  src/test/java/com/core/back9/mapper/ContractMapperTest.java
  src/test/java/com/core/back9/service/ContractServiceTest.java
Labels: development

#119 담당항목 Swagger 명세 구체화, 문서 공통 요소 및 링크 추가
  src/main/java/com/core/back9/common/config/SwaggerConfig.java
  src/main/java/com/core/back9/common/config/annotation/SwaggerAnnotationSpecification.java
  src/main/java/com/core/back9/controller/ContractController.java
  src/main/java/com/core/back9/controller/TenantController.java
  src/main/java/com/core/back9/controller/TenantPublicController.java
  src/main/java/com/core/back9/exception/ApiErrorCode.java
Labels: documentation, enhancement, development

#122 평가 북마크 오류 수정
  src/main/java/com/core/back9/repository/ScoreRepository.java
  src/main/java/com/core/back9/service/ScoreService.java
Labels: fix

#124 담당 항목 Swagger 명세 일부 수정
  src/main/java/com/core/back9/common/config/SwaggerConfig.java
  src/main/java/com/core/back9/common/config/annotation/SwaggerDocs.java
  src/main/java/com/core/back9/controller/ContractController.java
  src/main/java/com/core/back9/controller/TenantController.java
  src/test/java/com/core/back9/entity/ContractTest.java
Labels: enhancement, development

#125 컨트롤러별 Tag 추가
  src/main/java/com/core/back9/common/config/SwaggerConfig.java
  src/main/java/com/core/back9/controller/ContractController.java
Labels: development

#127 평가 조회 조건 수정
  src/main/java/com/core/back9/controller/OwnerScoreController.java
  src/main/java/com/core/back9/service/ScoreService.java
  src/main/java/com/core/back9/util/EvaluationSpecifications.java
Labels: development, fix

#129 actuator 의존성 설치 및 Health check 엔드포인트 작성
  build.gradle
  scripts/deploy.sh
  src/main/java/com/core/back9/common/actuator/HealthCheckController.java
  src/main/java/com/core/back9/common/actuator/ServerPortProvider.java
  src/main/java/com/core/back9/common/config/SwaggerConfig.java
  src/main/java/com/core/back9/service/ContractService.java
  src/main/resources/application.yml
Labels: documentation, enhancement

#134 회원가입, 로그인 시 입력값에 대한 검증 추가
  src/main/java/com/core/back9/dto/MemberDTO.java
Labels: development

#136 ssl 적용 위한 개선 작업
  .docker/docker-compose.yml
  scripts/deploy.sh
  src/main/java/com/core/back9/dto/TenantDTO.java
  src/main/java/com/core/back9/entity/Tenant.java
  src/main/java/com/core/back9/exception/ApiErrorCode.java
  src/main/java/com/core/back9/repository/TenantRepository.java
  src/main/java/com/core/back9/service/TenantService.java
Labels: documentation, enhancement

#138 평가 완료 상태를 확인하기 위한 평가 조회 API 추가
  src/main/java/com/core/back9/controller/UserScoreController.java
  src/main/java/com/core/back9/dto/ScoreDTO.java
  src/main/java/com/core/back9/repository/ScoreRepository.java
  src/main/java/com/core/back9/service/ScoreService.java
Labels: enhancement

#141 Tenant 생성 과정에서 발생하는 null체크 오류 수정
  src/main/java/com/core/back9/entity/Tenant.java
  src/main/java/com/core/back9/repository/TenantRepository.java
  src/main/java/com/core/back9/service/TenantService.java
Labels: development

#143 마지막 계약 기간이 1년이 넘는 계약이고 현재 진행중일 시 공실률이 -단위까지 조회되는 현상 개선
  scripts/deploy.sh
  src/main/java/com/core/back9/controller/ContractController.java
  src/main/java/com/core/back9/repository/RoomRepository.java
  src/main/java/com/core/back9/service/ContractService.java
  src/test/java/com/core/back9/service/ContractServiceTest.java
Labels: documentation, development, fix

#144 입주자 데모 앱에서 사용할 기능 추가
  src/main/java/com/core/back9/controller/AppUserContractController.java
  src/main/java/com/core/back9/controller/AppUserMemberController.java
  src/main/java/com/core/back9/controller/AppUserScoreController.java
  src/main/java/com/core/back9/dto/ContractDTO.java
  src/main/java/com/core/back9/dto/RoomDTO.java
  src/main/java/com/core/back9/mapper/ContractMapper.java
  src/main/java/com/core/back9/repository/ContractRepository.java
  src/main/java/com/core/back9/repository/MemberRepository.java
  src/main/java/com/core/back9/repository/ScoreRepository.java
  src/main/java/com/core/back9/service/ContractService.java
  src/main/java/com/core/back9/service/MemberService.java
  src/main/java/com/core/back9/service/ScoreService.java
Labels: enhancement

#148 빌딩 전체 조회 반환 형식 변경
  src/main/java/com/core/back9/controller/OwnerBuildingController.java
  src/main/java/com/core/back9/dto/BuildingDTO.java
  src/main/java/com/core/back9/mapper/BuildingMapper.java
  src/main/java/com/core/back9/repository/BuildingRepository.java
  src/main/java/com/core/back9/service/BuildingService.java
Labels: development

#151 Swagger Server별 url 수동 설정( local/dev )
  src/main/java/com/core/back9/common/config/SwaggerConfig.java
Labels: bug, documentation, development

#152 Swagger Profile별 url 자동 지정 기능 추가
  src/main/java/com/core/back9/common/config/SwaggerConfig.java
Labels: development

#153 평가 완료 여부 검증 관련 수정
  src/main/java/com/core/back9/controller/UserScoreController.java
  src/main/java/com/core/back9/dto/ScoreDTO.java
  src/main/java/com/core/back9/mapper/ScoreMapper.java
  src/main/java/com/core/back9/repository/ScoreRepository.java
  src/main/java/com/core/back9/service/ScoreService.java
  src/main/java/com/core/back9/util/EvaluationSpecifications.java
Labels: development, fix

#154 민원 관련 기능 구현
  src/main/java/com/core/back9/controller/AppUserComplaintController.java
  src/main/java/com/core/back9/dto/ComplaintDTO.java
  src/main/java/com/core/back9/dto/MemberDTO.java
  src/main/java/com/core/back9/entity/Complaint.java
  src/main/java/com/core/back9/entity/constant/ComplaintStatus.java
  src/main/java/com/core/back9/exception/ApiErrorCode.java
  src/main/java/com/core/back9/mapper/ComplaintMapper.java
  src/main/java/com/core/back9/repository/ComplaintRepository.java
  src/main/java/com/core/back9/repository/RoomRepository.java
  src/main/java/com/core/back9/service/ComplaintService.java
  src/main/resources/db/migration/common/V12__complaint-create.sql
Labels: enhancement

#156 로그 모니터링 처리 및 로그파일 관리 로직 작성
  .docker/docker-compose.yml
  src/main/java/com/core/back9/batch/job/TestBatchJob.java
  src/main/java/com/core/back9/batch/property/BatchPropertyConfig.java
  src/main/java/com/core/back9/batch/scheduler/TestBatchScheduler.java
  src/main/java/com/core/back9/batch/tasklet/TestTasklet.java
  src/main/java/com/core/back9/common/config/FilterConfig.java
  src/main/java/com/core/back9/common/config/SwaggerConfig.java
  src/main/java/com/core/back9/common/config/WebMvcConfig.java
  src/main/java/com/core/back9/common/logging/CachingFilter.java
  src/main/java/com/core/back9/common/logging/LoggingInterceptor.java
  src/main/java/com/core/back9/controller/OwnerRoomController.java
  src/main/java/com/core/back9/exception/ApiErrorCode.java
  src/main/java/com/core/back9/exception/ApiExceptionHandler.java
  src/main/java/com/core/back9/exception/ErrorResponse.java
  src/main/java/com/core/back9/repository/RoomRepository.java
  src/main/java/com/core/back9/repository/TenantRepository.java
  src/main/java/com/core/back9/service/RoomService.java
  src/main/resources/console-appender.xml
  src/main/resources/error-appender.xml
  src/main/resources/logback-spring.xml
Labels: documentation, enhancement, development

#158 알람 관련 기능 구현
  src/main/java/com/core/back9/controller/AppUserAlarmController.java
  src/main/java/com/core/back9/controller/SseController.java
  src/main/java/com/core/back9/dto/AlarmDTO.java
  src/main/java/com/core/back9/dto/ComplaintDTO.java
  src/main/java/com/core/back9/entity/Alarm.java
  src/main/java/com/core/back9/entity/Complaint.java
  src/main/java/com/core/back9/entity/Score.java
  src/main/java/com/core/back9/entity/constant/AlarmType.java
  src/main/java/com/core/back9/exception/ApiErrorCode.java
  src/main/java/com/core/back9/mapper/AlarmMapper.java
  src/main/java/com/core/back9/repository/AlarmRepository.java
  src/main/java/com/core/back9/service/AlarmService.java
  src/main/java/com/core/back9/service/ComplaintService.java
  src/main/java/com/core/back9/sse/connection/SseConnectionPool.java
  src/main/java/com/core/back9/sse/connection/SseConnectionPoolImpl.java
  src/main/java/com/core/back9/sse/connection/model/SseMemberConnection.java
  src/main/resources/db/migration/common/V13__alarm-create.sql
Labels: enhancement
